# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\escalation_template_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EscalationTemplateDialog(object):
    def setupUi(self, EscalationTemplateDialog):
        EscalationTemplateDialog.setObjectName("EscalationTemplateDialog")
        EscalationTemplateDialog.resize(400, 301)
        EscalationTemplateDialog.setStyleSheet("/* General window background */\n"
"QMainWindow {\n"
"    background-color: rgb(31, 31, 31);\n"
"    color: white; /* Default text color for all widgets */\n"
"}\n"
"\n"
"/* Styling for the tab widget container */\n"
"QTabWidget::pane {\n"
"    background: rgb(31, 31, 31); /* Background color of the whole tab area */\n"
"    border: none;\n"
"}\n"
"\n"
"/* Default tab styling */\n"
"QTabBar::tab {\n"
"    background: rgb(40, 40, 40); /* Default tab color */\n"
"    color: white; /* White text */\n"
"    padding: 10px;\n"
"    border: 1px solid rgb(60, 60, 60); /* Optional border */\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* Selected tab styling */\n"
"QTabBar::tab:selected {\n"
"    background: rgb(52, 52, 52); /* Selected tab color */\n"
"    color: rgb(255, 170, 0);\n"
"    border-bottom: 2px solid rgb(255, 170, 0); /* Highlight effect */\n"
"}\n"
"\n"
"/* Hover effect for tabs */\n"
"QTabBar::tab:hover {\n"
"    background: rgb(60, 60, 60);\n"
"}\n"
"\n"
"/* === TEXT WIDGET STYLING (WHITE TEXT DEFAULT) === */\n"
"QLabel, QTextEdit, QLineEdit, QCheckBox, QRadioButton, QListWidget, QTreeWidget, QTableWidget {\n"
"    color: white; /* All text is white by default */\n"
"}\n"
"\n"
"/* Styling for text input fields */\n"
"QTextEdit, QLineEdit {\n"
"    background-color: rgb(24, 24, 24);\n"
"    selection-background-color: rgb(52, 52, 52);\n"
"    selection-color: rgb(255, 170, 0);\n"
"    border: 1px solid rgb(60, 60, 60);\n"
"}\n"
"\n"
"/* === BUTTON STYLING === */\n"
"\n"
"/* Default button appearance */\n"
"QPushButton {\n"
"    background-color: rgb(40, 40, 40); /* Dark gray background */\n"
"    color: white; /* White text */\n"
"    border: 1px solid rgb(60, 60, 60); /* Subtle border */\n"
"    border-radius: 5px;\n"
"    padding: 8px 12px;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60); /* Lighter gray */\n"
"}\n"
"\n"
"/* Pressed/clicked effect */\n"
"QPushButton:pressed {\n"
"    background-color: rgb(52, 52, 52); /* Slightly darker */\n"
"}\n"
"\n"
"/* Disabled buttons */\n"
"QPushButton:disabled {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(150, 150, 150); /* Faded text */\n"
"}\n"
"\n"
"/* === QListWidget Styling === */\n"
"QListWidget {\n"
"    background-color: rgb(24, 24, 24); /* Dark background */\n"
"    border: 1px solid rgb(60, 60, 60); /* Subtle border */\n"
"    padding: 5px;\n"
"    color: white; /* Default text color */\n"
"}\n"
"\n"
"/* Individual QListWidget Items */\n"
"QListWidget::item {\n"
"    background-color: rgb(32, 32, 32);\n"
"    padding: 8px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"/* Selected item effect */\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(52, 52, 52);\n"
"    border: 1px solid rgb(255, 170, 0);\n"
"    color: rgb(255, 170, 0);\n"
"}\n"
"\n"
"/* === Scrollbar Styling (Optional, for QListWidget & other widgets) === */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(31, 31, 31);\n"
"    width: 10px;\n"
"    margin: 2px 2px 2px 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(60, 60, 60);\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(EscalationTemplateDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.EscalationTemplateGrid = QtWidgets.QGridLayout()
        self.EscalationTemplateGrid.setObjectName("EscalationTemplateGrid")
        self.EscalationTemplateTitle = QtWidgets.QLineEdit(EscalationTemplateDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EscalationTemplateTitle.setFont(font)
        self.EscalationTemplateTitle.setObjectName("EscalationTemplateTitle")
        self.EscalationTemplateGrid.addWidget(self.EscalationTemplateTitle, 0, 0, 1, 3)
        self.CloseEscalationTemplateButton = QtWidgets.QPushButton(EscalationTemplateDialog)
        self.CloseEscalationTemplateButton.setObjectName("CloseEscalationTemplateButton")
        self.EscalationTemplateGrid.addWidget(self.CloseEscalationTemplateButton, 2, 0, 1, 1)
        self.SaveAndCloseEscalationTemplateButton = QtWidgets.QPushButton(EscalationTemplateDialog)
        self.SaveAndCloseEscalationTemplateButton.setObjectName("SaveAndCloseEscalationTemplateButton")
        self.EscalationTemplateGrid.addWidget(self.SaveAndCloseEscalationTemplateButton, 2, 2, 1, 1)
        self.SaveEscalationTemplateButton = QtWidgets.QPushButton(EscalationTemplateDialog)
        self.SaveEscalationTemplateButton.setObjectName("SaveEscalationTemplateButton")
        self.EscalationTemplateGrid.addWidget(self.SaveEscalationTemplateButton, 2, 1, 1, 1)
        self.EscalationTemplateBody = QtWidgets.QTextEdit(EscalationTemplateDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EscalationTemplateBody.setFont(font)
        self.EscalationTemplateBody.setObjectName("EscalationTemplateBody")
        self.EscalationTemplateGrid.addWidget(self.EscalationTemplateBody, 1, 0, 1, 3)
        self.gridLayout_2.addLayout(self.EscalationTemplateGrid, 0, 0, 1, 1)

        self.retranslateUi(EscalationTemplateDialog)
        QtCore.QMetaObject.connectSlotsByName(EscalationTemplateDialog)

    def retranslateUi(self, EscalationTemplateDialog):
        _translate = QtCore.QCoreApplication.translate
        EscalationTemplateDialog.setWindowTitle(_translate("EscalationTemplateDialog", "Escalation Template"))
        self.EscalationTemplateTitle.setPlaceholderText(_translate("EscalationTemplateDialog", "Escalation Template Title"))
        self.CloseEscalationTemplateButton.setText(_translate("EscalationTemplateDialog", "Close"))
        self.SaveAndCloseEscalationTemplateButton.setText(_translate("EscalationTemplateDialog", "Save and Close"))
        self.SaveEscalationTemplateButton.setText(_translate("EscalationTemplateDialog", "Save"))
        self.EscalationTemplateBody.setPlaceholderText(_translate("EscalationTemplateDialog", "Escalation Template Body"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EscalationTemplateDialog = QtWidgets.QDialog()
    ui = Ui_EscalationTemplateDialog()
    ui.setupUi(EscalationTemplateDialog)
    EscalationTemplateDialog.show()
    sys.exit(app.exec_())
